[package]
name = "hdk-secure"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
cipher = "0.4"
ctr = "0.9.2"
cbc = "0.1"
ecb = "0.1"
uuid = { version = "1.19.0", features = ["v4"] }
crc16 = "0.4.0"
rand = "0.9.2"
hex = "0.4.3"

[features]
simd = []
